# Generated by Django 4.2.7 on 2023-11-10 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='profile_image',
            new_name='group_image',
        ),
    ]
