# Generated by Django 4.2.7 on 2023-11-13 12:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_profile_image_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.user_directory_path),
        ),
    ]
