# Generated by Django 4.2.7 on 2023-11-14 22:23

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.group_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=api.models.user_post_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=api.models.user_directory_path),
        ),
    ]
