# Generated by Django 4.2.7 on 2023-11-24 11:52

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_name', models.CharField(blank=True, max_length=120, null=True)),
                ('chat_picture', models.ImageField(blank=True, null=True, upload_to=api.models.chat_picture_upload_path)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='api.profile')),
                ('members', models.ManyToManyField(related_name='members', to='api.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=api.models.user_post_directory_path),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('attachement', models.ImageField(blank=True, null=True, upload_to=api.models.attachment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.profile')),
            ],
        ),
    ]
