# Generated by Django 4.2.7 on 2023-11-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_alter_post_attachment_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
